services:
  core:
    restart: unless-stopped
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - maven-cache:/root/.m2
    environment:
      - APP_VERSION
      - SERVER_URL
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_EXPIRATION_SECONDS=${JWT_EXPIRATION_SECONDS}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
volumes:
  maven-cache: