spring:
  application:
    name: twitter-api

  profiles:
    active: prod

  data:
    web:
      pageable:
        max-page-size: 50

api:
  security:
    token:
      secret: ${JWT_SECRET:secret}
      issuer: ${JWT_ISSUER:issuer}
      expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}