spring:
  application:
    name: twitter-api

  profiles:
    active: prod

api:
  security:
    token:
      secret: ${JWT_SECRET:secret}
      issuer: ${JWT_ISSUER:issuer}
      expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}