server:
  port: 8080

spring:
  application:
    name: twitter-api
    title: "Twitter API"
    version: "2.2.0"
  profiles:
    active: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  cache:
    type: NONE

  data:
    web:
      pageable:
        max-page-size: 50

api:
  security:
    token:
      secret: ${JWT_SECRET:secret}
      issuer: ${JWT_ISSUER:issuer}
      expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}